---
title: "ESM 204: Homework 2"
subtitle: "Simulating a Carbon Market"
author: "Kazie Mermel & Keene Morrow"
date: "4/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
```
# Saving to Git
1. Save your shit
2. Go to the Git tab
3. Click the little white boxes next to the stuff you want to send to the other person
4. Click Commit
5. Write a witty but descriptive commit message
6. Hit Commit!
7. *PUUUUUUULLLLLLL* then push
8. Profit


To comply with the Paris Accord, governments around the world are seeking ways to reduce carbon emissions. You have been asked to provide guidance on how country “X” can most efficiently reduce carbon emissions. In this homework you will conduct data analysis, simulations, and policy analysis to help inform this decision. The data for this assignment are available in the file “HW2Data.csv”, available on Gauchospace. The data contain estimates of the marginal cost of carbon abatement for four economic sectors (sectors A, B, C, and D), for different levels of abatement. A few notes:
 Current carbon emissions in the sectors are: (A=170, B=200, C=230, and D=300).
 Sectors A, B, and C are in country X. Sector D is in a different country, Y.
 Prices are in $/ton and quantities are in tons.

Your task is to produce a *1 page memo*, with supporting appendices, to advise country X (and in some questions, country Y) about how best to reduce carbon emissions. Your memo and appendices must address the following questions.
1. Start with sector A. Plot that sector’s marginal abatement cost estimates and write down a plausible functional form for the marginal cost of abatement. Use regression analysis to estimate the parameters of that function. Repeating this for sectors B, C, and D will give you a model of the marginal cost of abatement function for each sector. How well do your models fit the data for each sector? You may need to experiment with different functional forms, and you don’t necessarily have to assume the same function for each sector. Produce a plot of the estimated marginal abatement cost functions in all four sectors (this plot should go in your memo).

2. Using these models (i.e. use the functions you have estimated, not the data themselves) and the current level of carbon emissions (provided above), derive each sector’s demand curve for carbon emissions. In other words, how much would each sector be willing to pay for the right to pollute the first ton, second ton, etc.? Plot each sector’s demand curve for carbon emissions on a graph.

3. Now focus on country X (which contains sectors A, B, and C). Assume there are no “co-benefits” from carbon abatement (i.e. that there are no local pollutants that are affected by carbon abatement). Suppose to meet the Paris Accord commitments, country X needs to cut all carbon emissions in half. For each of the policy options listed below, derive: (1) the total cost of meeting the target in country X, (2) the cost (or benefit) to each sector, and (3) the tax revenue generated.

a. Cap on carbon. Each sector (A, B, and C) must cut its carbon emissions by 100 tons (thus reducing total emissions from 600 down to 300).

b. Tax on carbon. To emit a ton of carbon in country X, you must pay a tax of $t. You will need to find the tax that accomplishes the desired reduction.

*Notes from Section*
**Aggregate (Qa+Qb+Qc) must equal emissions goal. Find tax based off that value** 
**Linear model is okay as long as you say it's not the least R^2 value. Sam may give bonus points for non-linear**

c. Cap and trade. Each sector (A, B, C) is allocated carbon permits equal to their current emissions minus 100 (same as in (a) above), thus achieving the total reduction of 300. Then, these three sectors are allowed to trade with each other. You will need to derive the outcome of that trading.

4. Again, without any co-benefits, suppose that country Y (which only has one carbon-emitting sector, D) has no obligation to reduce its emissions. Country X asks country Y to enter the country X carbon market. Doing so would require country Y to put a cap on carbon emissions at its current level of emissions (300 tons), but would then allow country Y to sell carbon offsets to sectors A, B, and/or C. Are there any incentives for country Y to enter country X’s carbon market and to thus place a voluntary cap on its emissions? Are there any incentives for country X to try to attract country Y into its market? Describe these incentives as quantitatively as possible.